In [ ]:
print("The original string : " + test_string)
  
# using List comprehension + isdigit() +split()
# getting numbers from string 
res = [int(i) for i in test_string.split() if i.isdigit()]
  
# print result
print("The numbers list is : " + str(res))

In [2]:
import sys
print("Python version")
print (sys.version)

Python version
3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]


In [1]:
File_object = open(r"IN.txt")

In [2]:
x= File_object.readline()

In [4]:
a =File_object.readlines()

In [83]:
b=[]

In [84]:
for j in range (1,(len(a))):
    res = [int(i) for i in a[j].split() if i.isdigit()]
    b.append(res[0])    

In [72]:
b.append(res[0])

In [87]:
d = pd.DataFrame(b)

In [88]:
d.to_excel("GS.xlsx", index = False)

In [10]:

# import module
import requests 
import bs4 
  
# Taking thecity name as an input from the user
city = "Imphal"
  
# Generating the url  
  
# Sending HTTP request 
html = requests.get("https://www.familyeducation.com/baby-names/browse-origin/surname/german")

soup = BeautifulSoup(html.text, "html.parser")

metadata = soup.find_all('meta')

SSLError: HTTPSConnectionPool(host='www.familyeducation.com', port=443): Max retries exceeded with url: /baby-names/browse-origin/surname/german (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))

In [2]:
import pandas as pd

In [3]:
data = pd.read_excel('Haversine.xlsx', 'Sheet3', header=0, usecols = ('Branch','Lat', 'Long'))
Branch = pd.read_excel('Haversine.xlsx', 'Sheet3', header=0, usecols = ('Branch', 'Lat' ))

In [4]:
data1 = pd.read_excel('Haversine1.xlsx', 'Sheet7', header=0, usecols = ('Customer','Lat1', 'Long1'))
Customer = pd.read_excel('Haversine1.xlsx', 'Sheet7', header=0, usecols = ('Customer', 'Long1'))

In [3]:
data1 = pd.read_excel('Haversine1.xlsx', 'Sheet7')

In [4]:
data = pd.read_excel('Haversine.xlsx', 'Sheet3')

In [5]:
d1 = data.iloc[:,1:3].to_numpy()
d2 = data1.iloc[:,1:3].to_numpy()
result1 = tuple(map(tuple, d1))
result2 = tuple(map(tuple, d2))
# print result
#Customer = pd.read_excel('Haversine.xlsx', 'Sheet1', header=0, usecols = ('Customer'))

In [25]:
data.iloc[:,1:3]

Lat       Long
0     9.496266  76.347425
1    11.931042  79.787693
2    11.655788  78.163823
3     9.365692  78.829259
4    13.116139  80.289177
..         ...        ...
714  28.900660  76.586360
715  13.010883  80.141986
716  28.983690  77.021070
717  13.037090  80.228970
718  16.351630  78.057670

[719 rows x 2 columns]

In [6]:
def minimum(a, n):
  
    # inbuilt function to find the position of minimum 
    minpos = a.index(min(a))
      
    # inbuilt function to find the position of maximum 
    maxpos = a.index(max(a)) 
      
    # printing the position 
    #print ("The maximum is at position", maxpos + 1)  
    #print("The minimum is at position", minpos + 1)
    return minpos

In [13]:
Matrix = np.asmatrix(Matrix)

In [17]:
Matrix.shape()

TypeError: 'tuple' object is not callable

In [8]:
import numpy as np
w, h = len(data['Branch']), len(data1['Customer']);
#w, h =100,100;
listvals = []
distance = []
Matrix = [[0 for x in range(w)] for y in range(h)]
from haversine import haversine, Unit
for i in range (0,len(Customer['Customer'])):
    for j in range (0, len(Branch['Branch'])):
        Matrix[i][j] = haversine(result2[i],result1[j])
        if j == (len(Branch['Branch']) - 1):
            listvals.append((Customer['Customer'][i], Branch['Branch'][minimum(Matrix[i], len(Matrix[i]))]))
            #distance.append((Customer['Customer'][i],Matrix[i][minimum(Matrix[i], len(Matrix[i]))]))

In [5]:
result2 = (9.1794, 79.4183)
result1 = (9.087340729151904, 79.71022652722986)

In [6]:
from haversine import haversine
haversine(result2,result1)

33.64431922589518

In [64]:
minimum(Matrix[0], len(Matrix[0]))

723

In [9]:
t = pd.DataFrame(listvals, columns =["Customer", "Branch"])
t = t.dropna()
#t.to_excel("Bran_7.xlsx", index = False)

In [30]:
import modin.pandas as pd
import ray
import os
os.environ["MODIN_ENGINE"] = "ray"

In [33]:
u.head()

Customer   Distance
0             M/S MAHA LAKSHMI CONVENTION CENTRE  24.629959
1                              ANDHRA BOOK STALL  24.629959
2              AV QUALITY MANAGEMENT CONSULTANCY  24.629959
3  M/S SHRAVAN RAJ CONSTRUCTIONS PRIVATE LIMITED  24.629959
4                             SRI BALAJI CANTEEN  24.629959

In [10]:
t.to_excel('sBrNmAP.xlsx')

In [ ]:
#import modin.pandas as pd
writer = pd.ExcelWriter('dist12.xlsx', engine='xlsxwriter')

# Convert the dataframe to an XlsxWriter Excel object.
u.to_excel(writer, sheet_name='Sheet1')

# Close the Pandas Excel writer and output the Excel file.
writer.save()

In [8]:
u = pd.DataFrame(distance, columns =["Customer", "Distance"])
u = u.dropna()

In [17]:
df1 = pd.read_excel('Haversine.xlsx', 'Sheet3', header=0, usecols = ('Branch', 'Br_code'))

In [18]:
in1 = pd.merge(t,df1,on ='Branch',how ='inner')

In [19]:
df2 = pd.read_excel("BBU.xlsx", 'Division', usecols = ('Division', 'Br_code'))

In [20]:
in2 = pd.merge(in1,df2,on ='Br_code',how ='inner')

In [21]:
df3 = pd.read_excel("BBU.xlsx", 'BBU', usecols = ('Division', 'Div', 'Br_code'))
df4 = pd.read_excel("BBU.xlsx", 'CBU', usecols = ('Division', 'Div', 'Br_code'))

In [22]:
in3 = pd.merge(in2,df3,on ='Division',how ='left')

In [23]:
in4 = pd.merge(in3,df4,on ='Division',how ='left')

In [27]:
in5.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 546317 entries, 0 to 546316
Data columns (total 9 columns):
 #   Column     Non-Null Count   Dtype  
---  ------     --------------   -----  
 0   Customer   546317 non-null  object 
 1   Branch     546317 non-null  object 
 2   Br_code_x  546317 non-null  int64  
 3   Division   546317 non-null  object 
 4   Div_x      423370 non-null  object 
 5   Br_code_y  423370 non-null  float64
 6   Div_y      397699 non-null  object 
 7   Br_code    397699 non-null  float64
 8   Owner      0 non-null       object 
dtypes: float64(2), int64(1), object(6)
memory usage: 41.7+ MB


In [25]:
df5 = pd.read_excel("EMP_Bran.xlsx", 'Owner', usecols = ('Br_code', 'Owner'))

In [26]:
in5 = pd.merge(in4,df5,on ='Br_code',how ='left')

In [132]:
df6 = pd.read_excel('emp_det_KVB.xlsx', 'BBH', header=0, usecols = ('emp_code', 'Br_code_y'))
df7 = pd.read_excel('emp_det_KVB.xlsx', 'CBH', header=0, usecols = ('emp_code', 'Br_code'))

In [138]:
in6 = pd.merge(in5,df6,on ='Br_code_y', how ='left')
in7 = pd.merge(in6,df7,on ='Br_code', how ='left')

In [ ]:
in5.to_excel("bii.xlsx", index = False)

Exception ignored in: <function ZipFile.__del__ at 0x00000223FF8CA8B0>
Traceback (most recent call last):
  File "d:\lib\zipfile.py", line 1807, in __del__
    self.close()
  File "d:\lib\zipfile.py", line 1815, in close
    if self._writing:
AttributeError: 'ZipFile' object has no attribute '_writing'


In [31]:
in4 = pd.merge(in3,df4,on ='Division',how ='inner')

In [7]:
u = pd.DataFrame(distance, columns =["A", "B"])
u.to_excel("dist_7.xlsx", index = False)

In [60]:
res = []
for tup in result1:
    temp = []
    for ele in tup:
          
        # check for string
        if ele.isalpha():
            temp.append(ele)
        else:
              
            # convert to float
            temp.append(float(ele))
    res.append((temp[0],temp[1]))
  

AttributeError: 'numpy.float64' object has no attribute 'isalpha'

In [42]:
import vaex
import pandas as pd
import numpy as np
n_rows = 1000000
n_cols = 1000
df = pd.DataFrame(np.random.randint(0, 100, size=(n_rows, n_cols)), columns=['col%d' % i for i in range(n_cols)])

In [15]:
minimum(Matrix[0], len(Matrix[0]))

202

In [73]:
t = pd.DataFrame(listvals, columns =["A", "B"])
t.to_excel("Bran3.xlsx", index = False)

In [125]:
t.head()

A                   B
0                    YOGENDER SINGH           GHAZIABAD
1                      TALOR MASTER             GURGAON
2                     APS FURNITURE          KARIMNAGAR
3                 Dinesh Embroidery  DELHI - KAROL BAGH
4  M/S ORIENTAL FERRO ALLOYS PVTLTD  DELHI - KAROL BAGH

In [4]:
import numpy as np
listvals = []
for i in range(10):
    listvals.append((1, 2))
mat_vls = np.vstack(mat_vals)

In [5]:
mat_vls

array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2]])

In [93]:
t = pd.DataFrame(listvals, columns =["A", "B"])

In [66]:
t.to_excel("Bran1.xlsx", index = False)

In [56]:
result2[1]

(27.1205, 79.3574)

In [54]:
data.head()

Lat     Long
0  16.1548  80.1028
1  17.9065  78.2970
2  13.3718  79.9360
3  17.6673  82.6104
4  18.3538  78.5573

In [55]:
data1.head()

Lat1    Long1
0  27.9204  78.1458
1  27.1205  79.3574
2  27.7372  79.1863
3  28.6516  77.1886
4  28.6094  76.9439

In [7]:
arr1 = numpy.arange(8).reshape(2, 4)
print("2D arr1 : \n", arr1)
print("Shape : ", arr1.shape)

2D arr1 : 
 [[0 1 2 3]
 [4 5 6 7]]
Shape :  (2, 4)


In [19]:
a = numpy.insert(arr1, [1],[4], axis = 0)
a

array([[0, 1, 2, 3],
       [4, 4, 4, 4],
       [4, 5, 6, 7]])

In [26]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0, 1])

2


In [34]:
w, h = 8, 5;
Matrix = [[0 for x in range(w)] for y in range(h)] 

In [35]:
Matrix[0][0] = 1

In [37]:
Matrix[0]

[1, 0, 0, 0, 0, 0, 0, 0]

In [150]:
type(haversine(result1[1],result2[1]))

float

In [132]:
for (i, j) in data.iteritems():
    print('Column Name : ', i)
    #print('Column Value : ', type(j[0]))
    x = tuple(map(tuple, i[0]))

Column Name :  Branch
Column Name :  India_Dist
Column Name :  Lat
Column Name :  Long
Column Name :  Customer
Column Name :  Lat1
Column Name :  Long1


In [131]:
x

(('L',),)

In [ ]:
for (columnName, columnData) in stu_df.iteritems():
    print('Column Name : ', columnName)
    print('Column Contents : ', columnData.values)

In [ ]:
haversine(lyon, paris)