In [11]:
import pandas as pd
from tensorflow import keras
from tensorflow.keras import layers
from kerastuner.tuners import RandomSearch
import keras_tuner

In [4]:
import pandas as pd
import numpy as np 
data = pd.read_excel('CnoHmln.xlsx', 'Sheet1')

In [12]:
from numpy import mean
from numpy import std
from sklearn.datasets import make_multilabel_classification
from sklearn.model_selection import RepeatedKFold
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import (confusion_matrix,
                           accuracy_score)
 
# get the dataset
# get the model
def get_model(n_inputs, n_outputs):
	model = Sequential()
	model.add(Dense(20, input_dim=n_inputs, kernel_initializer='he_uniform', activation='relu'))
	model.add(Dense(n_outputs, activation='sigmoid'))
	#model.add(Flatten())
	model.compile(loss='binary_crossentropy', optimizer='adam')
	return model
 

 
# load dataset
bank_cust = data.copy()
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
numeric_subset = data[['TOTDR','TOTCR','CTDR','CTCR', 'AGE', 'COD_KYC_RISK_CATEGORY']]#.apply(pd.to_numeric)
#numeric_subset = numeric_subset.apply(le.fit_transform)
categorical_subset = data[['V_BRANCH_NAME','CUST_PROFESSION', 'TXT_CUST_SEX']]
    # One hot encoding
categorical_subset = pd.get_dummies(categorical_subset)
    # Join the two dataframes using concat
bank_cust = pd.concat([numeric_subset, categorical_subset], axis = 1)
#X = bank_cust.drop(['HL'], axis = 1)
X = bank_cust
y = pd.DataFrame(data['HL'])

results = list()
n_inputs, n_outputs = X.shape[1], 1
# define evaluation procedure
from sklearn import metrics
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)
# define model
model = get_model(n_inputs, n_outputs)
# fit model

In [23]:
model.fit(X_train, y_train, verbose=0, epochs=100)
# make a prediction on the test set
prediction = model.predict(X_test)
# round probabilities to class labels
prediction = prediction.round()
cm = confusion_matrix(y_test, prediction)
# calculate accuracy
acc = accuracy_score(y_test, prediction)
# store result
print('>%.3f' % acc)
results.append(acc)
# summarize performance
print('Accuracy: %.3f (%.3f)' % (mean(results), std(results)))

>0.880
Accuracy: 0.880 (0.001)


In [24]:
cm

array([[38258,   152],
       [ 5104,   407]], dtype=int64)

In [ ]:
import pandas as pd
import numpy as np 
data1 = pd.read_excel('Ctest1.xlsx', 'Sheet2')
bank_cust = data1.copy()
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
numeric_subset = data1[['TOTDR','TOTCR','CTDR','CTCR', 'AGE', 'COD_KYC_RISK_CATEGORY']]#.apply(pd.to_numeric)
numeric_subset = numeric_subset.apply(le.fit_transform)
categorical_subset = data1[['V_BRANCH_NAME','CUST_PROFESSION', 'TXT_CUST_SEX']]
    # One hot encoding
categorical_subset = pd.get_dummies(categorical_subset)
    # Join the two dataframes using concat
bank_cust = pd.concat([numeric_subset, categorical_subset], axis = 1)
#X = bank_cust.drop(['HL'], axis = 1)
bank_cust1 = bank_cust.copy()
# for y in X_train.columns:
#     if (y not in bank_cust.columns):
#         bank_cust1[y] = [0]*len(bank_cust1)
X = bank_cust1[X_train.columns]                       
y = data1['HL']

In [22]:
prediction = model.predict(X)
prediction = prediction.round()
from sklearn.metrics import (confusion_matrix,
                           accuracy_score)
# confusion matrix
cm = confusion_matrix(y, prediction)
print ("Confusion Matrix : \n", cm)
# accuracy score of the model
print('Test accuracy = ', accuracy_score(y, prediction))

Confusion Matrix : 
 [[124813   3066]
 [   371      1]]
Test accuracy =  0.973200988686248


In [21]:
prediction

array([[0.0000000e+00],
       [1.1094707e-01],
       [2.9688221e-30],
       ...,
       [1.1094707e-01],
       [1.0168541e-27],
       [0.0000000e+00]], dtype=float32)

In [27]:
X, y = make_multilabel_classification(n_samples=1000, n_features=10, n_classes=3, n_labels=2, random_state=1)

In [19]:
prediction

array([[0.0000000e+00],
       [1.1094707e-01],
       [2.9688221e-30],
       ...,
       [1.1094707e-01],
       [1.0168541e-27],
       [0.0000000e+00]], dtype=float32)

In [5]:
df=pd.read_csv('Real_Combine.csv')

In [6]:
df.head()

T    TM   Tm     SLP     H   VV    V    VM      PM 2.5
0   7.4   9.8  4.8  1017.6  93.0  0.5  4.3   9.4  219.720833
1   7.8  12.7  4.4  1018.5  87.0  0.6  4.4  11.1  182.187500
2   6.7  13.4  2.4  1019.4  82.0  0.6  4.8  11.1  154.037500
3   8.6  15.5  3.3  1018.7  72.0  0.8  8.1  20.6  223.208333
4  12.4  20.9  4.4  1017.3  61.0  1.3  8.7  22.2  200.645833

In [7]:
X=df.iloc[:,:-1] ## independent features
y=df.iloc[:,-1] ## dependent features

In [2]:
import pandas as pd
import numpy as np 
data = pd.read_excel('CnoHmln.xlsx', 'Sheet1')

In [21]:
bank_cust = data.copy()
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
numeric_subset = data[['TOTDR','TOTCR','CTDR','CTCR', 'AGE', 'COD_KYC_RISK_CATEGORY']]#.apply(pd.to_numeric)
#numeric_subset = numeric_subset.apply(le.fit_transform)
categorical_subset = data[['V_BRANCH_NAME','CUST_PROFESSION', 'TXT_CUST_SEX']]
    # One hot encoding
categorical_subset = pd.get_dummies(categorical_subset)
    # Join the two dataframes using concat
bank_cust = pd.concat([numeric_subset, categorical_subset], axis = 1)
#X = bank_cust.drop(['HL'], axis = 1)
X = bank_cust
y = data['HL']

#### Hyperparameters
1. How many number of hidden layers we should have?
2. How many number of neurons we should have in hidden layers?
3. Learning Rate 

In [4]:
def build_model(hp):
    model = keras.Sequential()
    for i in range(hp.Int('num_layers', 2, 20)):
        model.add(layers.Dense(units=hp.Int('units_' + str(i),
                                            min_value=32,
                                            max_value=512,
                                            step=32),
                               activation='relu'))
    model.add(layers.Dense(1, activation='linear'))
    model.compile(
        optimizer=keras.optimizers.Adam(
            hp.Choice('learning_rate', [1e-2, 1e-3, 1e-4])),
        loss='mean_absolute_error',
        metrics=['mean_absolute_error'])
    return model

In [5]:
tuner = RandomSearch(
    build_model,
    objective='val_mean_absolute_error',
    max_trials=5,
    executions_per_trial=3,
    directory='project',
    project_name='Air Quality Index')

INFO:tensorflow:Reloading Oracle from existing project project\Air Quality Index\oracle.json
INFO:tensorflow:Reloading Tuner from project\Air Quality Index\tuner0.json


In [6]:
tuner.search_space_summary()

Search space summary
Default search space size: 21
num_layers (Int)
{'default': None, 'conditions': [], 'min_value': 2, 'max_value': 20, 'step': 1, 'sampling': None}
units_0 (Int)
{'default': None, 'conditions': [], 'min_value': 32, 'max_value': 512, 'step': 32, 'sampling': None}
units_1 (Int)
{'default': None, 'conditions': [], 'min_value': 32, 'max_value': 512, 'step': 32, 'sampling': None}
learning_rate (Choice)
{'default': 0.01, 'conditions': [], 'values': [0.01, 0.001, 0.0001], 'ordered': True}
units_2 (Int)
{'default': None, 'conditions': [], 'min_value': 32, 'max_value': 512, 'step': 32, 'sampling': None}
units_3 (Int)
{'default': None, 'conditions': [], 'min_value': 32, 'max_value': 512, 'step': 32, 'sampling': None}
units_4 (Int)
{'default': None, 'conditions': [], 'min_value': 32, 'max_value': 512, 'step': 32, 'sampling': None}
units_5 (Int)
{'default': None, 'conditions': [], 'min_value': 32, 'max_value': 512, 'step': 32, 'sampling': None}
units_6 (Int)
{'default': None, 'co

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [8]:
tuner.search(X_train, y_train,
             epochs=5,
             validation_data=(X_test, y_test))

INFO:tensorflow:Oracle triggered exit


In [10]:
tuner.results_summary()

Results summary
Results in project\Air Quality Index
Showing 10 best trials
Objective(name='val_mean_absolute_error', direction='min')
Trial summary
Hyperparameters:
num_layers: 19
units_0: 416
units_1: 352
learning_rate: 0.01
units_2: 224
units_3: 416
units_4: 320
units_5: 224
units_6: 64
units_7: 320
units_8: 64
units_9: 64
units_10: 288
units_11: 224
units_12: 224
units_13: 448
units_14: 480
units_15: 96
units_16: 416
units_17: 512
units_18: 32
Score: nan
Trial summary
Hyperparameters:
num_layers: 3
units_0: 448
units_1: 416
learning_rate: 0.0001
units_2: 384
units_3: 192
units_4: 480
units_5: 64
units_6: 512
units_7: 64
units_8: 320
Score: nan
Trial summary
Hyperparameters:
num_layers: 18
units_0: 384
units_1: 64
learning_rate: 0.01
units_2: 320
units_3: 352
units_4: 256
units_5: 480
units_6: 352
units_7: 416
units_8: 256
units_9: 32
units_10: 32
units_11: 32
units_12: 32
units_13: 32
units_14: 32
units_15: 32
units_16: 32
units_17: 32
Score: nan
Trial summary
Hyperparameters:
num_