In [1]:
import numpy as np
from sklearn.model_selection import RepeatedKFold
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([0, 0, 1, 1])
rkf = RepeatedKFold(n_splits=2, n_repeats=2, random_state=2652124)
for train_index, test_index in rkf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

TRAIN: [0 1] TEST: [2 3]
TRAIN: [2 3] TEST: [0 1]
TRAIN: [1 2] TEST: [0 3]
TRAIN: [0 3] TEST: [1 2]


In [12]:
import numpy as np
from sklearn.model_selection import RepeatedKFold
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([0, 0, 1, 1])
rkf = RepeatedKFold(n_splits=3, n_repeats=1, random_state=26521)
for train_index, test_index in rkf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

TRAIN: [1 2] TEST: [0 3]
TRAIN: [0 1 3] TEST: [2]
TRAIN: [0 2 3] TEST: [1]


In [13]:
from sklearn.linear_model import SGDClassifier
X = [[0., 0.], [1., 1.]]
y = [0, 1]
clf = SGDClassifier(loss="hinge", penalty="l2", max_iter=5)
clf.fit(X, y)
SGDClassifier(max_iter=5)

D:\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:574: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn("Maximum number of iteration reached before "


SGDClassifier(max_iter=5)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [77]:
dataset.groupby('SA_STAT').sum()

CA_STAT  RD_STAT  TD_STAT  VEHICLELN_STAT  OTHER_STAT  NONFUND_STAT  \
SA_STAT                                                                        
0          22349     2191    15097            2637           0          4888   
1          25523    63568   140836           12320           0           621   

         HL_STAT  DEPOSITLN_STAT  EDULN_STAT  AGRITERMLN_STAT  ...  \
SA_STAT                                                        ...   
0            558            6747           2              138  ...   
1          13909            9400         738             2321  ...   

         HEALTHINSUR_FLG  LOCKER_FLG  POS_FLG  BIJLI_FLG  BHARATQR_FLG  \
SA_STAT                                                                  
0                    365        1517     8826       3212          4891   
1                   5704       70162     1034        329          1306   

         PMJJBY_FLG  PMSBY_FLG  SGB_FLG  CORP_CC_FLG  RET_CC_FLG  
SA_STAT                                                           
0              1040       1331       24          142         128  
1            111695     132963      950         2307        6290  

[2 rows x 40 columns]

In [4]:
len(dataset.columns)

41

In [9]:
import pandas as pd
import numpy as np
dataset = pd.read_csv('PPC_New1.csv', index_col = "V_CUST_CODE")
# input
x = dataset.iloc[:, np.arange(39)].values
# output
y = dataset.iloc[:, 40].values

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x, y)
y_pred = classifier.predict(x)

In [11]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y, y_pred)
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[485498    250]
 [  6167    251]]


In [39]:
d = dataset[[dataset.columns[2], dataset.columns[3], dataset.columns[4]]]
d.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 492166 entries, 37413 to 26468147
Data columns (total 3 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   RD_STAT         492166 non-null  int64
 1   TD_STAT         492166 non-null  int64
 2   VEHICLELN_STAT  492166 non-null  int64
dtypes: int64(3)
memory usage: 31.1 MB


In [ ]:
d['y_pred'] = y_pred

In [ ]:
import xgboost as xgb
xgb = xgb.XGBClassifier(objective = 'binary:logitraw') 
xgb.fit(x, y)
xgb_pred = xgb.predict(x) 

In [56]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y, xgb_pred)
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[477209      0]
 [ 14957      0]]


In [78]:
tn, fp, fn, tp = confusion_matrix(y, xgb_pred).ravel()
(tn, fp, fn, tp)

(477209, 0, 14957, 0)

In [12]:
from sklearn.ensemble import RandomForestClassifier
 # create regressor object
regressor = RandomForestClassifier(n_estimators = 100, random_state = 0)
# fit the regressor with x and y data
regressor.fit(x, y)
Y_pre = regressor.predict(x)

In [68]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y, Y_pre)
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[477209      0]
 [ 14957      0]]


In [ ]:
np.array([[6.5, 7.6],
       [6.5, 7.6]]).reshape(3,2)