In [ ]:
import os
os.getcwd()

In [3]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(random_state=0)
X = [[ 1,  2,  3, 4],  # 2 samples, 3 features
     [11, 12, 13,14]]
y = [0, 1]  # classes of each sample
clf.fit(X, y)

RandomForestClassifier(random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler
X = [[0, 15],
     [1, -10]]
# scale data according to computed scaling values
StandardScaler().fit(X).transform(X)

array([[-1.,  1.],
       [ 1., -1.]])

In [12]:
import pandas as pd
X = pd.DataFrame(
    {'city': ['London', 'London', 'Paris', 'Sallisaw'],
     'title': ["His Last Bow", "How Watson Learned the Trick",
               "A Moveable Feast", "The Grapes of Wrath"],
     'expert_rating': [5, 3, 4, 5],
     'user_rating': [4, 5, 4, 3]})

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import OneHotEncoder
column_trans = ColumnTransformer(
    [('city_category', OneHotEncoder(dtype='int'),['city']),
     ('title_bow', CountVectorizer(), 'title')],
    remainder='drop')

In [18]:
column_trans.fit(X)

column_trans.get_feature_names()

column_trans.transform(X).toarray()

array([[1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0],
       [0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1]], dtype=int64)

In [20]:
from sklearn.preprocessing import StandardScaler
from sklearn.compose import make_column_selector
import numpy as np
ct = ColumnTransformer([
      ('scale', StandardScaler(),
      make_column_selector(dtype_include=np.number)),
      ('onehot',
      OneHotEncoder(),
      make_column_selector(pattern='city', dtype_include=object))])
ct.fit_transform(X)

array([[ 0.90453403,  0.        ,  1.        ,  0.        ,  0.        ],
       [-1.50755672,  1.41421356,  1.        ,  0.        ,  0.        ],
       [-0.30151134,  0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.90453403, -1.41421356,  0.        ,  0.        ,  1.        ]])

In [ ]:
import dash
import dash_html_components as html
import dash_core_components as dcc
from dash.dependencies import Input, Output


external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']

app = dash.Dash(__name__, external_stylesheets=external_stylesheets)
app.layout = html.Div([
    dcc.Dropdown(
        id='dropdown',
        options=[
            {'label': 'New York City', 'value': 'NYC'},
            {'label': 'Montreal', 'value': 'MTL'},
            {'label': 'San Francisco', 'value': 'SF'}
        ],
        value='NYC'
    ),
    dcc.Store(id='intermediate-value'),
    html.Div(id='dd-output-container'),
    html.Div(id='container')
])


@app.callback(
    dash.dependencies.Output('dd-output-container', 'children'),
    [dash.dependencies.Input('dropdown', 'value')])
def update_output(value):
    return 'You have selected "{}"'.format(value)

@app.callback(
    dash.dependencies.Output('container', 'children'),
    [dash.dependencies.Input('intermediate-value', 'data')])
def update_output(value):
    return 'You have selected "{}"'.format(value)


@app.callback(Output('intermediate-value', 'data'), Input('dropdown', 'value'))
def clean_data(value):
     # some expensive clean data step
     cleaned_df = value

     # more generally, this line would be
     # json.dumps(cleaned_df)
     return cleaned_df

if __name__ == '__main__':
    app.run_server(debug=True, use_reloader=False)

In [1]:
import numpy as np
import math

# Create random input and output data
x = np.linspace(-math.pi, math.pi, 2000)
y = np.sin(x)

In [3]:
a = np.random.randn()
b = np.random.randn()
c = np.random.randn()
d = np.random.randn()

learning_rate = 1e-6

In [12]:
x.sum()

-2.2737367544323206e-13

In [14]:
import numpy as np
import math

# Create random input and output data
x = np.linspace(-math.pi, math.pi, 2000)
y = np.sin(x)

# Randomly initialize weights
a = np.random.randn()
b = np.random.randn()
c = np.random.randn()
d = np.random.randn()

learning_rate = 1e-6
for t in range(2000):
    # Forward pass: compute predicted y
    # y = a + b x + c x^2 + d x^3
    y_pred = a + b * x + c * x ** 2 + d * x ** 3

    # Compute and print loss
    loss = np.square(y_pred - y).sum()
    if t % 100 == 99:
        print(t, loss)

    # Backprop to compute gradients of a, b, c, d with respect to loss
    grad_y_pred = 2.0 * (y_pred - y)
    grad_a = grad_y_pred.sum()
    grad_b = (grad_y_pred * x).sum()
    grad_c = (grad_y_pred * x ** 2).sum()
    grad_d = (grad_y_pred * x ** 3).sum()

    # Update weights
#     a -= learning_rate * grad_a
#     b -= learning_rate * grad_b
#     c -= learning_rate * grad_c
#     d -= learning_rate * grad_d

# print(f'Result: y = {a} + {b} x + {c} x^2 + {d} x^3')

99 91106.65405747878
199 91106.65405747878
299 91106.65405747878
399 91106.65405747878
499 91106.65405747878
599 91106.65405747878
699 91106.65405747878
799 91106.65405747878
899 91106.65405747878
999 91106.65405747878
1099 91106.65405747878
1199 91106.65405747878
1299 91106.65405747878
1399 91106.65405747878
1499 91106.65405747878
1599 91106.65405747878
1699 91106.65405747878
1799 91106.65405747878
1899 91106.65405747878
1999 91106.65405747878


In [19]:
loss

91106.65405747878

In [ ]:
import django
print(django.get_version())

In [ ]:
pip install newspaper3k

In [35]:
from newspaper import Article

url = 'https://news.google.com/articles/CBMigwFodHRwczovL2VuZXJneS5lY29ub21pY3RpbWVzLmluZGlhdGltZXMuY29tL25ld3MvcG93ZXIvNTAtcGVyLWNlbnQtb2YtbnBjaWxzLWdlbmVyYXRpb24taW4tc291dGgtc2h1dC1kb3duLWZvci1tYWludGVuYW5jZS84Mzc3NTUxN9IBhwFodHRwczovL2VuZXJneS5lY29ub21pY3RpbWVzLmluZGlhdGltZXMuY29tL2FtcC9uZXdzL3Bvd2VyLzUwLXBlci1jZW50LW9mLW5wY2lscy1nZW5lcmF0aW9uLWluLXNvdXRoLXNodXQtZG93bi1mb3ItbWFpbnRlbmFuY2UvODM3NzU1MTc?hl=en-US&gl=US&ceid=US%3Aen'
article = Article(url)
article.download()

In [36]:
article.parse()
article.authors


[]

In [37]:
(article.publish_date)

In [38]:
article.text

"Accept the updated privacy & cookie policy\n\nDear user,\n\n\n\nET EnergyWorld privacy and cookie policy has been updated to align with the new data regulations in European Union. Please review and accept these changes below to continue using the website.\n\n\n\nYou can see our privacy policy & our cookie policy. We use cookies to ensure the best experience for you on our website.\n\n\n\nIf you choose to ignore this message, we'll assume that you are happy to receive all cookies on ET EnergyWorld."

In [12]:
import newspaper

In [13]:
cnn_paper = newspaper.build('https://news.google.com/articles/CAIiEDl-uKIl-uk2TPJ_Xw4PVJIqGQgEKhAIACoHCAow55veCjDzvdUBMOLc5gU?uo=CAUiwAFodHRwczovL3d3dy5maW5hbmNpYWxleHByZXNzLmNvbS9tYXJrZXQvc2hhcmUtbWFya2V0LXRvZGF5LWxpdmUtdXBkYXRlcy1zZW5zZXgtbmlmdHktcnVwZWUtdnMtZG9sbGFyLXNneC1uaWZ0eS1pcG9zLXNoeWFtLW1ldGFsaWNzLWRvZGxhLWRhaXJ5LWtpbXMtdXMtZmVkZXJhbC1yZXNlcnZlLTE3LWp1bmUtdGh1cnNkYXkvMjI3Mjg2Mi_SAQA&hl=en-US&gl=US&ceid=US%3Aen')

In [14]:
for article in cnn_paper.articles:
    print(article.url)

https://www.financialexpress.com/market/stock-market/state-bank-of-india-stock-price/
https://www.financialexpress.com/market/stock-market/housing-development-finance-corporation-ltd-stock-price/
https://www.financialexpress.com/market/stock-market/tata-consultancy-services-ltd-stock-price/
https://www.financialexpress.com/market/commodities/gold-price-today-17-june-2021-tanks-to-one-month-low-post-us-fomc-outcome-mcx-silver-below-rs-71000/2272921/
https://www.financialexpress.com/market/stock-market/global-vectra-helicorp-ltd-stock-price/
https://www.financialexpress.com/market/stock-market/healthcare-global-enterprises-ltd-stock-price/
https://www.financialexpress.com/market/stock-market/hindustan-media-ventures-ltd-stock-price/
https://www.financialexpress.com/market/stock-market/ifb-agro-industries-ltd-stock-price/
https://www.financialexpress.com/market/stock-market/indostar-capital-finance-ltd-stock-price/
https://www.financialexpress.com/market/stock-market/nava-bharat-ventures-

In [15]:
for category in cnn_paper.category_urls():
    print(category)

https://news.google.com/articles/CAIiEDl-uKIl-uk2TPJ_Xw4PVJIqGQgEKhAIACoHCAow55veCjDzvdUBMOLc5gU?uo=CAUiwAFodHRwczovL3d3dy5maW5hbmNpYWxleHByZXNzLmNvbS9tYXJrZXQvc2hhcmUtbWFya2V0LXRvZGF5LWxpdmUtdXBkYXRlcy1zZW5zZXgtbmlmdHktcnVwZWUtdnMtZG9sbGFyLXNneC1uaWZ0eS1pcG9zLXNoeWFtLW1ldGFsaWNzLWRvZGxhLWRhaXJ5LWtpbXMtdXMtZmVkZXJhbC1yZXNlcnZlLTE3LWp1bmUtdGh1cnNkYXkvMjI3Mjg2Mi_SAQA&hl=en-US&gl=US&ceid=US%3Aen
https://play.google.com


In [16]:
cnn_article = cnn_paper.articles[0]

In [19]:
cnn_article.url

'https://www.financialexpress.com/market/stock-market/state-bank-of-india-stock-price/'

In [ ]:

datetime.datetime(2013, 12, 30, 0, 0)

>>> article.text
'Washington (CNN) -- Not everyone subscribes to a New Year's resolution...'

>>> article.top_image
'http://someCDN.com/blah/blah/blah/file.png'

>>> article.movies
['http://youtube.com/path/to/link.com', ...]

In [24]:
cnn_article = cnn_paper.articles[0]
cnn_article.download()
cnn_article.parse()
cnn_article.nlp()

In [23]:
cnn_article.text

''