In [8]:
import pandas as pd
data = pd.read_csv('PPC_New1.csv', index_col = "V_CUST_CODE")

In [ ]:
df.groupby('Description').agg(
    orders=('InvoiceNo', 'nunique'),
    quantity=('Quantity', 'sum')).sort_values(by='orders', ascending=False).head(10)

In [10]:
def get_recommendations(df, item):
    """Generate a set of product recommendations using item-based collaborative filtering.
    
    Args:
        df (dataframe): Pandas dataframe containing matrix of items purchased.
        item (string): Column name for target item. 
        
    Returns: 
        recommendations (dataframe): Pandas dataframe containing product recommendations. 
    """
    
    recommendations = df.corrwith(df[item])
    recommendations.dropna(inplace=True)
    recommendations = pd.DataFrame(recommendations, columns=['correlation']).reset_index()
    recommendations = recommendations.sort_values(by='correlation', ascending=False)
    recommendations['correlation'] = recommendations['correlation'].apply(lambda x: round(x, 3))
    return recommendations

In [3]:
d = data[((data[a[0][1]]==1) & (data[a[0][0]]==1))]
s = a[0][1]+','+a[0][0]
d[s]=1
e = data[((data[a[0][1]]==0) & (data[a[0][0]]==0))]
s = a[0][1]+','+a[0][0]
e[s]=0
d = pd.concat([d,e])

NameError: name 'a' is not defined

In [95]:
data.columns[0]

'CA_STAT'

In [ ]:
get_recommendations(data, data.columns[0])[get_recommendations(data, data.columns[0])['correlation']!=1.000]
#get_recommendations[get_recommendations(data, data.columns[1])['correlation']!=1.00]

In [77]:
gr = get_recommendations(data, data.columns[1])
#[get_recommendations(data, data.columns[1])['correlation']!=float(1.000000)]

In [ ]:
get_recommendations(data, data.columns[1])

In [ ]:
get_recommendations(d, d.columns[i])[get_recommendations(d, d.columns[i])['correlation']!=1.000]

In [11]:
a = []
aa=[]
for i in range(len(data.columns)):
    try:
        a.append((data.columns[i],get_recommendations(data, data.columns[i])[get_recommendations(data, data.columns[i])['correlation']!=1.000].iloc[0,0], get_recommendations(data, data.columns[i])[get_recommendations(data, data.columns[i])['correlation']!=1.000].iloc[0,1]))
        aa.append(i)
    except:
  #a.append((data.columns[i+1],get_recommendations(data, data.columns[i+1]).iloc[1,0], get_recommendations(data, data.columns[i+1]).iloc[1,1]))
          print(i)
a=[]        
for i in aa:
    a.append((data.columns[i],get_recommendations(data, data.columns[i])[get_recommendations(data, data.columns[i])['correlation']!=1.000].iloc[0,0], get_recommendations(data, data.columns[i])[get_recommendations(data, data.columns[i])['correlation']!=1.000].iloc[0,1]))

5


In [ ]:
for i in range(len(a)):
    d = data[((data[a[i][1]]==1) & (data[a[i][0]]==1))]
    s = a[i][1]+','+a[i][0]
    d[s]=1
    e = data[((data[a[i][1]]==0) & (data[a[i][0]]==0))]
    s = a[i][1]+','+a[i][0]
    e[s]=0
    d = pd.concat([d,e])
    d = d.drop([a[i][1]], axis=1)
    d = d.drop([a[i][0]], axis=1)
    b = []
    bb=[]
    for i in range(len(a)):
        try:
            b.append((s,get_recommendations(d, s)[get_recommendations(d, s)['correlation']!=1.000].iloc[0,0], get_recommendations(d, s)[get_recommendations(d, s)['correlation']!=1.000].iloc[0,1]))
            bb.append(i)
        except:
              print(i)
#a.append((d.columns[i+1],get_recommendations(d, d.columns[i+1]).iloc[1,0], get_recommendations(d, d.columns[i+1]).iloc[1,1])) 
    b=[]        
    for i in bb:
          b.append((s,get_recommendations(d, s)[get_recommendations(d, s)['correlation']!=1.000].iloc[0,0], get_recommendations(d, s)[get_recommendations(d, s)['correlation']!=1.000].iloc[0,1]))

In [22]:
i=22
d = data[((data[a[i][1]]==1) & (data[a[i][0]]==1))]
s = a[i][1]+','+a[i][0]
d[s]=1
e = data[((data[a[i][1]]==0) & (data[a[i][0]]==0))]
s = a[i][1]+','+a[i][0]
e[s]=0
d = pd.concat([d,e])
d = d.drop([a[i][1]], axis=1)
d = d.drop([a[i][0]], axis=1)

In [ ]:
c=[]
for i in range(len(a)):
    d = data[((data[a[i][1]]==1) & (data[a[i][0]]==1))]
    s = a[i][1]+','+a[i][0]
    d[s]=1
    e = data[((data[a[i][1]]==0) & (data[a[i][0]]==0))]
    s = a[i][1]+','+a[i][0]
    e[s]=0
    d = pd.concat([d,e])
    d = d.drop([a[i][1]], axis=1)
    d = d.drop([a[i][0]], axis=1)
    c.append((s,get_recommendations(d, s)[get_recommendations(d, s)['correlation']!=1.000].iloc[0,0], get_recommendations(d, s)[get_recommendations(d, s)['correlation']!=1.000].iloc[0,1]))
#     b = []
#     bb=[]
#     try:
#         b.append((s,get_recommendations(d, s)[get_recommendations(d, s)['correlation']!=1.000].iloc[0,0], get_recommendations(d, s)[get_recommendations(d, s)['correlation']!=1.000].iloc[0,1]))
#         bb.append(i)
#     except:
#           print(i)
# #a.append((d.columns[i+1],get_recommendations(d, d.columns[i+1]).iloc[1,0], get_recommendations(d, d.columns[i+1]).iloc[1,1])) 
       
#     for i in bb:
#           c.append((s,get_recommendations(d, s)[get_recommendations(d, s)['correlation']!=1.000].iloc[0,0], get_recommendations(d, s)[get_recommendations(d, s)['correlation']!=1.000].iloc[0,1]))

In [58]:
b = []
bb=[]
for i in range(len(d.columns)):
    try:
        b.append((d.columns[i],get_recommendations(d, d.columns[i]).iloc[1,0], get_recommendations(d, d.columns[i]).iloc[1,1]))
        bb.append(i)
    except:
        print(i)
  #a.append((d.columns[i+1],get_recommendations(d, d.columns[i+1]).iloc[1,0], get_recommendations(d, d.columns[i+1]).iloc[1,1])) 
b=[]        
for i in bb:
    b.append((d.columns[i],get_recommendations(d, d.columns[i]).iloc[1,0], get_recommendations(d, d.columns[i]).iloc[1,1]))

5


In [32]:
d[d['DEMAT_FLG,RET_CC_FLG']==1]

CA_STAT  SA_STAT  RD_STAT  TD_STAT  VEHICLELN_STAT  OTHER_STAT  \
V_CUST_CODE                                                                   
1961102            0        1        0        0               0           0   
2193598            0        1        0        0               0           0   
4051526            0        1        1        1               0           0   
4095519            0        1        1        0               0           0   
4776476            0        1        0        0               0           0   
...              ...      ...      ...      ...             ...         ...   
8996234            0        1        0        0               0           0   
9008765            0        1        0        1               0           0   
10143261           0        1        0        0               0           0   
11247290           0        1        0        1               0           0   
11271877           0        1        0        0               0           0   

             NONFUND_STAT  HL_STAT  DEPOSITLN_STAT  EDULN_STAT  ...  \
V_CUST_CODE                                                     ...   
1961102                 0        0               0           0  ...   
2193598                 0        0               0           0  ...   
4051526                 0        0               0           0  ...   
4095519                 0        0               0           0  ...   
4776476                 0        0               0           0  ...   
...                   ...      ...             ...         ...  ...   
8996234                 0        0               0           0  ...   
9008765                 0        0               0           0  ...   
10143261                0        0               0           0  ...   
11247290                0        0               0           0  ...   
11271877                0        0               0           0  ...   

             HEALTHINSUR_FLG  LOCKER_FLG  POS_FLG  BIJLI_FLG  BHARATQR_FLG  \
V_CUST_CODE                                                                  
1961102                    0           0        0          0             0   
2193598                    0           0        0          0             0   
4051526                    0           0        0          0             0   
4095519                    0           0        0          0             0   
4776476                    0           0        0          0             0   
...                      ...         ...      ...        ...           ...   
8996234                    0           1        0          0             0   
9008765                    0           0        0          0             0   
10143261                   0           0        0          0             0   
11247290                   0           0        0          0             0   
11271877                   0           0        0          0             1   

             PMJJBY_FLG  PMSBY_FLG  SGB_FLG  CORP_CC_FLG  DEMAT_FLG,RET_CC_FLG  
V_CUST_CODE                                                                     
1961102               1          1        0            0                     1  
2193598               0          1        0            1                     1  
4051526               0          0        0            0                     1  
4095519               0          0        0            0                     1  
4776476               0          0        0            1                     1  
...                 ...        ...      ...          ...                   ...  
8996234               0          1        0            0                     1  
9008765               1          1        0            0                     1  
10143261              1          1        0            0                     1  
11247290              0          0        0            0                     1  
11271877              0          0        0            0                  

In [26]:
get_recommendations(d,'OTHER_STAT')

Empty DataFrame
Columns: [index, correlation]
Index: []

In [ ]:
get_recommendations(d, d.columns[8])

In [ ]:
b = []
for i in range(len(d.columns)):
    try:
        b.append((d.columns[i],get_recommendations(d, d.columns[i]).iloc[1,0]))
    except:
        try:
            b.append((d.columns[i+1],get_recommendations(d, d.columns[i+1]).iloc[1,0]))
        except:
            b.append((d.columns[i+1],get_recommendations(d, d.columns[i+1]).iloc[1,0]))
            print(i)

In [104]:
d.columns

Index(['CA_STAT', 'SA_STAT', 'RD_STAT', 'TD_STAT', 'VEHICLELN_STAT',
       'OTHER_STAT', 'NONFUND_STAT', 'HL_STAT', 'DEPOSITLN_STAT', 'EDULN_STAT',
       'AGRITERMLN_STAT', 'GOVTSCH_STAT', 'WC_LN_STAT', 'WAREHOUSELN_STAT',
       'AGRIJEWELLN_STAT', 'EXPORTCR_STAT', 'MORTLN_STAT', 'BILLS_DC_STAT',
       'TERMLN_STAT', 'AGRI_WC_STAT', 'OTHER_LN_STAT', 'TOD_STAT',
       'AGRI_NONJEWEL_STAT', 'PROF_LN_STAT', 'PL_STAT', 'JEWEL_LN_STAT',
       'FASTAG_FLG', 'MUTUALFND_FLG', 'LIFEINSUR_FLG', 'NONLIFEINSUR_FLG',
       'HEALTHINSUR_FLG', 'LOCKER_FLG', 'POS_FLG', 'BIJLI_FLG', 'BHARATQR_FLG',
       'PMJJBY_FLG', 'PMSBY_FLG', 'SGB_FLG', 'CORP_CC_FLG', 'RET_CC_FLG',
       'DEMAT_FLG,RET_CC_FLG'],
      dtype='object')

In [112]:
get_recommendations(d, d.columns[37]).iloc[1,0]

'RD_STAT'

In [ ]:
get_recommendations(d, 'EXPORTCR_STAT')

In [63]:

a = []
for i in range(len(data.columns)):
    try:
        a.append((data.columns[i],get_recommendations(data, data.columns[i]).iloc[1,0]))
    except:
        a.append((data.columns[i+1],get_recommendations(data, data.columns[i+1]).iloc[1,0]))
        print(i)

In [ ]:
import pandas as pd
data = pd.read_excel('file.xlsx', sheet_name=1)
data

In [ ]:
data.groupby(by="V_PROD_DESC").count()

In [94]:
import numpy as np

def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum()

scores = [3.0, 3.0, 1.0, 0.2]
print(softmax(scores))

[0.45534327 0.45534327 0.06162401 0.02768945]


In [105]:
data['AVGBAL'].sum()

2799343.2800000003

In [ ]:
(data['AVGBAL']/data['AVGBAL'].sum())*5

In [97]:
data['C_AVGBAL'] = softmax(data['AVGBAL'])

In [98]:
df = data[['V_CUST_CODE','V_PROD_DESC','C_AVGBAL']]

In [ ]:
pd.pivot_table(df, values='C_AVGBAL', index=['V_CUST_CODE'], columns=['V_PROD_DESC'])

In [5]:
x = [[3.,1.],
       [1., 3.],
       [4.,3.],
    [5.,3.],
    [100.,13.]]

In [7]:
x = [[3.,1., 1.],
       [1., 3., 2.]]

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled = scaler.fit_transform(x)
scaler.transform(x)

array([[ 1., -1., -1.],
       [-1.,  1.,  1.]])

In [136]:
softmax(scaler.transform(x))

array([[9.74794302e-15, 7.14405930e-15],
       [5.01215612e-15, 1.14109572e-14],
       [1.35943103e-14, 1.14109572e-14],
       [1.89583866e-14, 1.14109572e-14],
       [1.00000000e+00, 1.18633461e-13]])

In [4]:
import numpy as np
y = x-np.median(x)/(np.percentile(x, 75)-np.percentile(x, 25))
y

array([[ 1.28571429, -0.71428571],
       [-0.71428571,  1.28571429],
       [ 2.28571429,  1.28571429],
       [ 3.28571429,  1.28571429],
       [98.28571429, 11.28571429]])

In [127]:
x=[3,1,4,5,100,1,3,3,3,13]

In [128]:
import numpy as np
np.percentile(x, 25)

3.0

In [129]:
np.percentile(x, 75)

4.75

In [114]:
import numpy as np

def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum()

scores = [3.0, 1.0, 0.2]
scores = np.array(scores).reshape(-1,1)
print(softmax(x))

[[0.06955066 0.00941266]
 [0.00941266 0.06955066]
 [0.1890583  0.06955066]
 [0.51391374 0.06955066]]


In [ ]:
from sklearn.preprocessing import StandardScaler
#X = np.array(df['deceduti']).reshape(-1,1)
scaler = StandardScaler()
scaler.fit(x)
X_scaled = scaler.transform(x)
X_scaled
#df['z score'] = X_scaled.reshape(1,-1)[0]

In [29]:
import numpy as np
from sklearn.preprocessing import MaxAbsScaler
#x = np.array(x).reshape(-1,1)
scaler = MaxAbsScaler()
scaler.fit(x)
X_scaled = scaler.transform(x)

In [20]:
d.sort_values(by = ['V_ACCT_NO', 'Fic'], ascending = [False, True], na_position = 'first')

Fic         V_ACCT_NO  N_INT_RATE V_MODULE_ID    STATUS  RATE  \
28 2022-03-31  1104115000018080       17.35         NaN       NaN   NaN   
29 2022-06-30  1104115000018080       17.75         TOD  STANDARD  MCLR   
19 2022-03-31  1104115000016790       16.75         TOD       NPA  MCLR   
20 2022-04-30  1104115000016790       17.35         TOD       NPA  MCLR   
21 2022-05-31  1104115000016790       17.35         TOD       NPA  MCLR   

    AVG_BAL  
28   750.37  
29   285.99  
19  6555.21  
20  6555.21  
21  6555.21

In [ ]:
import numpy as np
#inds = pd.isnull(df).any(1).nonzero()[0]
index = d['STATUS'].index[d['STATUS'].apply(np.isnan)]
index

In [72]:
fruits = list(pd.isnull(d['Unnamed: 5']))
fruits.index(True)

18

In [ ]:
d.index[d['STATUS'].apply(np.isnan)]